export const dataArray = [
  {
    id: 1,
    firstName: "Harry",
    lastName: "potter",
    gender: "M",
    house: "Nebelvír",
    year: 2,
  },
  {
    id: 2,
    firstName: "hermiona",
    lastName: "Granger",
    gender: "F",
    house: "Nebelvír",
    year: 2,
  },
  {
    id: 3,
    firstName: "Ron",
    lastName: "Weasley",
    gender: "M",
    house: "Nebelvír",
    year: 2,
  },
  {
    id: 4,
    firstName: "Ginny",
    lastName: "Weasley",
    gender: "F",
    house: "Nebelvír",
    year: 1,
  },
  {
    id: 5,
    firstName: "Luna",
    lastName: "Lovegood",
    gender: "F",
    house: "Havraspár",
    year: 1,
  },
  {
    id: 6,
    firstName: "Draco",
    lastName: "Malfoy",
    gender: "M",
    house: "Zmijozel",
    year: 2,
  },
];
